"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, Banknote, BarChart3, BriefcaseBusiness, CalendarDays, Clock3, RefreshCw, Sparkles, UsersRound, WalletCards } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Point={date:string;label:string;value:number;year:number;month:number};
type Industry={id:string;label:string;wage:Point[];employment:Point[];latestWage:number;latestEmployment:number;wageYoY:number;employmentYoY:number};
type Data={indicators:Record<string,Point[]>;industries:Industry[];fetchedAt:string;latestPeriod:string};
const COLORS=["#c6ff42","#ff8a3d","#7dd3fc","#c084fc","#facc15","#4ade80","#fb7185","#60a5fa","#a3e635","#f472b6"];
const months=Array.from({length:36},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(35-i));return{date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,label:d.toLocaleDateString("en-US",{month:"short",year:"2-digit"}),value:31+i*.18+Math.sin(i/3)*.55,year:d.getFullYear(),month:d.getMonth()+1}});
const fallback:Data={latestPeriod:"Jul 2026",fetchedAt:new Date().toISOString(),indicators:{unemployment:months.map((p,i)=>({...p,value:4.2+Math.sin(i/4)*.18})),participation:months.map((p,i)=>({...p,value:62.4+Math.sin(i/5)*.15})),privateWage:months,weeklyHours:months.map(p=>({...p,value:34.3+Math.sin(p.month)*.08})),nonfarm:months.map((p,i)=>({...p,value:157000+i*125}))},industries:[
  ["information","Information",49.8,3050,3.8],["finance","Financial activities",43.6,9220,4.1],["mining","Mining & logging",39.7,640,3.2],["professional","Professional & business",39.2,22950,3.6],["construction","Construction",38.1,8340,4.5],["manufacturing","Manufacturing",33.7,12730,3.4],["education","Education & health",32.4,26820,4.8],["trade","Trade, transport & utilities",30.2,29150,3.1],["other","Other services",29.1,6050,3.7],["leisure","Leisure & hospitality",23.6,17120,4.2],
].map(([id,label,wage,employment,yoy],i)=>({id:id as string,label:label as string,latestWage:wage as number,latestEmployment:employment as number,wageYoY:yoy as number,employmentYoY:1.1+i*.11,wage:months.map((p,j)=>({...p,value:(wage as number)*(1-(35-j)*.0027)+Math.sin(j/4)*.16})),employment:months.map((p,j)=>({...p,value:(employment as number)*(1-(35-j)*.0008)}))}))};

const last=(series?:Point[])=>series?.at(-1)?.value||0;
const money=(v:number)=>`$${v.toFixed(2)}`;
const compact=(v:number)=>Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(v);
function Delta({value}:{value:number}){const up=value>=0;return <span className={`delta ${up?"up":"down"}`}>{up?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(value).toFixed(1)}%</span>}
function ChartTip({active,payload,label,moneyMode=false,suffix=""}:any){if(!active||!payload?.length)return null;return <div className="chart-tip"><strong>{label}</strong>{payload.map((p:any)=><div key={p.dataKey}><i style={{background:p.color}}/><span>{p.name}</span><b>{moneyMode?money(p.value):compact(p.value)}{suffix}</b></div>)}</div>}

export default function Home(){
  const[data,setData]=useState<Data>(fallback);const[live,setLive]=useState(false);const[loading,setLoading]=useState(true);const[selectedId,setSelectedId]=useState("information");const[payMode,setPayMode]=useState("hourly");
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/labor",{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json());setLive(true)}catch{setData(fallback);setLive(false)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
  const selected=data.industries.find(i=>i.id===selectedId)||data.industries[0];
  const hours=last(data.indicators.weeklyHours);const unemployment=last(data.indicators.unemployment),participation=last(data.indicators.participation),privateWage=last(data.indicators.privateWage),nonfarm=last(data.indicators.nonfarm);
  const indicatorYoy=(key:string)=>{const s=data.indicators[key]||[],c=s.at(-1)?.value,p=s.at(-13)?.value;return c!=null&&p!=null&&p?(c-p)/p*100:0};
  const ranking=useMemo(()=>[...data.industries].sort((a,b)=>b.latestWage-a.latestWage).map((i,index)=>({...i,rank:index+1,fill:COLORS[index]})),[data]);
  const trend=useMemo(()=>selected.wage.map((p,i)=>({...p,hourly:p.value,weekly:p.value*hours,employment:selected.employment[i]?.value})),[selected,hours]);
  const market=useMemo(()=>data.industries.map((i,index)=>({name:i.label,wage:i.latestWage,employment:i.latestEmployment,size:Math.max(70,Math.sqrt(i.latestEmployment)*4),fill:COLORS[index]})),[data]);
  const average=data.industries.reduce((s,i)=>s+i.latestWage,0)/Math.max(data.industries.length,1);
  return <main className="app">
    <header><div className="brand"><div className="mark"><WalletCards/></div><div><b>SalaryScope</b><span>U.S. LABOR MARKET</span></div></div><div className="header-meta"><span className={`feed ${live?"":"demo"}`}><i/>{live?"LIVE BLS":"DEMO DATA"}</span><button onClick={load} disabled={loading} aria-label="Refresh"><RefreshCw className={loading?"spin":""}/></button></div></header>
    <section className="ticker"><div><Sparkles/>LATEST RELEASE <b>{data.latestPeriod}</b></div><div className="ticker-items"><span>PRIVATE PAY <b>{money(privateWage)}/HR</b></span><span>WEEKLY EST. <b>{money(privateWage*hours)}</b></span><span>NONFARM JOBS <b>{compact(nonfarm*1000)}</b></span></div></section>
    <div className="dashboard">
      <div className="title-row"><div><p>PAY & EMPLOYMENT MONITOR</p><h1>Where the money <em>meets the market.</em></h1></div><div className="period"><CalendarDays/><span>UPDATED<br/><b>{new Date(data.fetchedAt).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</b></span></div></div>
      <section className="kpis"><Kpi icon={<Banknote/>} label="Private hourly pay" value={money(privateWage)} note="Average hourly earnings" delta={indicatorYoy("privateWage")}/><Kpi icon={<Clock3/>} label="Estimated weekly pay" value={money(privateWage*hours)} note={`${hours.toFixed(1)} average hours`} delta={indicatorYoy("privateWage")}/><Kpi icon={<BriefcaseBusiness/>} label="Unemployment" value={`${unemployment.toFixed(1)}%`} note="Civilian labor force" delta={indicatorYoy("unemployment")} inverse/><Kpi icon={<UsersRound/>} label="Participation" value={`${participation.toFixed(1)}%`} note="Working-age population" delta={indicatorYoy("participation")}/></section>
      <section className="main-grid">
        <article className="panel ranking"><PanelHead title="Industry pay leaderboard" subtitle="Average hourly earnings by major private sector" extra={<span className="unit">USD / HOUR</span>}/><div className="rank-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={ranking} layout="vertical" margin={{top:10,right:32,left:12,bottom:4}}><CartesianGrid stroke="#263342" horizontal={false} strokeDasharray="4 5"/><XAxis type="number" domain={[0,"dataMax + 6"]} tickFormatter={v=>`$${v}`} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:12}}/><YAxis type="category" dataKey="label" width={158} axisLine={false} tickLine={false} tick={{fill:"#d9e2eb",fontSize:12}}/><Tooltip content={<ChartTip moneyMode/>}/><Bar dataKey="latestWage" name="Hourly pay" radius={[0,7,7,0]} barSize={18}>{ranking.map(i=><Cell key={i.id} fill={i.fill}/>)}</Bar></BarChart></ResponsiveContainer></div></article>
        <article className="panel focus"><PanelHead title="Sector focus" subtitle="Pay trend for selected industry"/><Select value={selectedId} onValueChange={setSelectedId}><SelectTrigger className="sector-select"><SelectValue/></SelectTrigger><SelectContent>{data.industries.map(i=><SelectItem key={i.id} value={i.id}>{i.label}</SelectItem>)}</SelectContent></Select><div className="focus-number"><span>{payMode==="hourly"?"CURRENT HOURLY":"EST. WEEKLY"}</span><b>{payMode==="hourly"?money(selected.latestWage):money(selected.latestWage*hours)}</b><Delta value={selected.wageYoY}/></div><Tabs value={payMode} onValueChange={setPayMode}><TabsList className="pay-tabs"><TabsTrigger value="hourly">Hourly</TabsTrigger><TabsTrigger value="weekly">Weekly</TabsTrigger></TabsList></Tabs><div className="focus-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:16,right:8,left:4,bottom:0}}><defs><linearGradient id="payFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#c6ff42" stopOpacity={.38}/><stop offset="1" stopColor="#c6ff42" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#263342" vertical={false} strokeDasharray="4 5"/><XAxis dataKey="label" interval={5} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:11}}/><YAxis domain={["dataMin - 2","dataMax + 2"]} tickFormatter={v=>`$${Math.round(v)}`} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:11}} width={43}/><Tooltip content={<ChartTip moneyMode/>}/><Area type="monotone" dataKey={payMode} name={payMode==="hourly"?"Hourly pay":"Weekly pay"} stroke="#c6ff42" strokeWidth={2.5} fill="url(#payFill)"/></AreaChart></ResponsiveContainer></div></article>
      </section>
      <section className="lower-grid">
        <article className="panel trend-panel"><PanelHead title="Private-pay momentum" subtitle="Hourly earnings across the private economy" extra={<Delta value={indicatorYoy("privateWage")}/>}/><div className="wide-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.indicators.privateWage} margin={{top:18,right:20,left:3,bottom:2}}><CartesianGrid stroke="#263342" vertical={false} strokeDasharray="4 5"/><XAxis dataKey="label" interval={5} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:11}}/><YAxis domain={["dataMin - 1","dataMax + 1"]} tickFormatter={v=>`$${v}`} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:11}} width={48}/><Tooltip content={<ChartTip moneyMode/>}/><Bar dataKey="value" name="Hourly pay" fill="#314252" radius={[4,4,0,0]} barSize={10}/><Line dataKey="value" name="Pay trend" type="monotone" stroke="#ff8a3d" strokeWidth={2.4} dot={false}/></ComposedChart></ResponsiveContainer></div></article>
        <article className="panel gauge-panel"><PanelHead title="Labor snapshot" subtitle="Current workforce conditions"/><div className="meter"><div className="meter-head"><span>Labor participation</span><b>{participation.toFixed(1)}%</b></div><div className="track"><i style={{width:`${participation}%`}}/></div></div><div className="meter danger"><div className="meter-head"><span>Unemployment</span><b>{unemployment.toFixed(1)}%</b></div><div className="track"><i style={{width:`${Math.min(unemployment*10,100)}%`}}/></div></div><div className="snapshot-row"><span><b>{hours.toFixed(1)}</b> hours / week</span><span><b>{compact(nonfarm*1000)}</b> nonfarm jobs</span></div></article>
      </section>
      <section className="panel market-panel"><PanelHead title="Pay versus workforce size" subtitle="Each bubble is a major private industry; farther right means more jobs" extra={<span className="benchmark">AVG PAY <b>{money(average)}</b></span>}/><div className="scatter"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:25,right:35,left:10,bottom:14}}><CartesianGrid stroke="#263342" strokeDasharray="4 5"/><XAxis type="number" dataKey="employment" name="Employment" tickFormatter={v=>`${Math.round(v/1000)}M`} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:12}}/><YAxis type="number" dataKey="wage" name="Hourly pay" domain={[15,"dataMax + 5"]} tickFormatter={v=>`$${v}`} axisLine={false} tickLine={false} tick={{fill:"#6d7d8f",fontSize:12}}/><ZAxis type="number" dataKey="size" range={[100,750]}/><ReferenceLine y={average} stroke="#7f8c99" strokeDasharray="5 5"/><Tooltip cursor={{strokeDasharray:"4 4"}} content={({active,payload}:any)=>active&&payload?.length?<div className="bubble-tip"><b>{payload[0]?.payload?.name}</b><span>{money(payload[0]?.payload?.wage)}/hr</span><span>{compact(payload[0]?.payload?.employment*1000)} jobs</span></div>:null}/><Scatter data={market}>{market.map(m=><Cell key={m.name} fill={m.fill}/>)}</Scatter></ScatterChart></ResponsiveContainer></div></section>
      <footer><span>Source: U.S. Bureau of Labor Statistics · CES and CPS series</span><span>Seasonally adjusted where published · Values may be revised</span></footer>
    </div>
  </main>
}
function Kpi({icon,label,value,note,delta,inverse=false}:{icon:React.ReactNode;label:string;value:string;note:string;delta:number;inverse?:boolean}){const shown=inverse?-delta:delta;return <article className="kpi"><div className="kpi-icon">{icon}</div><div className="kpi-body"><span>{label}</span><b>{value}</b><small>{note}</small></div><Delta value={shown}/></article>}
function PanelHead({title,subtitle,extra}:{title:string;subtitle:string;extra?:React.ReactNode}){return <div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div>{extra}</div>}
