"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip as ChartTooltip,XAxis,YAxis,ZAxis} from "recharts";
import {AlertTriangle,Car,ChevronRight,CloudRain,Eye,MapPinned,Navigation,RefreshCw,Route,ShieldCheck,Snowflake,Thermometer,TrafficCone,Wind} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";

type Incident={id:string;road:string;type:string;subtype:string;severity:string;description:string;location:string;direction:string;lanes:string;region:string;lat:number|null;lon:number|null;updated:number};
type Road={id:string;road:string;location:string;condition:string;visibility:string;drifting:string;region:string;updated:number};
type Weather={id:string;city:string;temp:number|null;condition:string;humidity:number|null;wind:number|null;windDir:string;lat:number|null;lon:number|null};
type Data={incidents:Incident[];roads:Road[];weather:Weather[];updatedAt:string;partial?:boolean};
const REGION_COLORS:Record<string,string>={Central:"#ffd83d",Eastern:"#54b3ff",Northeastern:"#8cd17d",Northwestern:"#b388eb",Southwestern:"#ff8b5c",Ontario:"#aeb8c2"};
const color=(region:string)=>Object.entries(REGION_COLORS).find(([k])=>region.toLowerCase().includes(k.toLowerCase()))?.[1]??"#aeb8c2";
const ago=(t:number)=>{const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`};
const conditionGroup=(s:string)=>/dry/i.test(s)?"Bare & dry":/wet|slush/i.test(s)?"Wet / slushy":/snow/i.test(s)?"Snow covered":/ice|icy/i.test(s)?"Icy":"Other";
function fallback():Data{const regions=["Central","Eastern","Northeastern","Northwestern","Southwestern"];const cities=[[-79.38,43.65,"Toronto",22,"Partly cloudy",14],[-75.70,45.42,"Ottawa",20,"Light rain",18],[-89.25,48.38,"Thunder Bay",15,"Cloudy",22],[-80.49,43.45,"Kitchener",21,"Mainly sunny",12],[-83.04,42.31,"Windsor",24,"Clear",17],[-79.87,43.26,"Hamilton",22,"Cloudy",19],[-84.33,46.52,"Sault Ste. Marie",16,"Showers",24],[-78.86,43.90,"Oshawa",21,"Partly cloudy",15]] as const;const incidents=Array.from({length:24},(_,i)=>({id:`demo-i${i}`,road:["401","400","417","11","17","QEW","402"][i%7],type:["Collision","Roadwork","Closure","Hazard"][i%4],subtype:"",severity:["Minor","Moderate","Major"][i%3],description:["Lane restrictions in effect","Collision blocking right lane","Planned maintenance activity","Road closed for investigation"][i%4],location:["near Toronto","at Kingston Road","west of Ottawa","near Sudbury","at Kenora"][i%5],direction:["Eastbound","Westbound","Northbound","Southbound"][i%4],lanes:i%3===0?"Right lane":"Shoulder",region:regions[i%5],lat:42.4+(i*1.17)%8.8,lon:-94+(i*3.7)%18,updated:Date.now()-i*19*60000}));const roads=Array.from({length:58},(_,i)=>({id:`demo-r${i}`,road:["401","17","11","69","417","7"][i%6],location:`Sector ${i+1}`,condition:["Bare and dry road","Bare and wet road","Partly snow covered","Snow packed","Icy sections"][i%5],visibility:["Good","Fair","Poor"][i%3],drifting:i%9===0?"Yes":"No",region:regions[i%5],updated:Date.now()-i*37*60000}));const weather=cities.map((c,i)=>({id:`demo-w${i}`,lon:c[0],lat:c[1],city:c[2],temp:c[3],condition:c[4],humidity:55+i*4,wind:c[5],windDir:["NW","W","SE","N"][i%4]}));return{incidents,roads,weather,updatedAt:new Date().toISOString()}}
function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}>{children}</section>}
function Tip({active,payload}:{active?:boolean;payload?:Array<{payload:any;name:string;value:number}>}){if(!active||!payload?.length)return null;const d=payload[0].payload;return <div className="tip"><strong>{d.city??`${d.road} · ${d.type}`??d.name}</strong><span>{d.location??d.condition??`${d.temp}°C`}</span></div>}

export default function Home(){
 const[data,setData]=useState<Data>(fallback);const[status,setStatus]=useState<"loading"|"live"|"snapshot">("loading");const[region,setRegion]=useState("All Ontario");const[view,setView]=useState("network");const[selected,setSelected]=useState("");const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{setRefreshing(true);try{const r=await fetch("/api/travel",{cache:"no-store"});if(!r.ok)throw new Error();const p=await r.json();if(!p.incidents?.length&&!p.roads?.length)throw new Error();setData(p);setStatus("live");if(!selected&&p.incidents[0])setSelected(p.incidents[0].id)}catch{setStatus("snapshot")}finally{setRefreshing(false)}},[selected]);useEffect(()=>{load();const x=window.setInterval(load,300000);return()=>window.clearInterval(x)},[]);
 const match=(r:string)=>region==="All Ontario"||r.toLowerCase().includes(region.toLowerCase());const incidents=useMemo(()=>data.incidents.filter(i=>match(i.region)),[data.incidents,region]);const roads=useMemo(()=>data.roads.filter(r=>match(r.region)),[data.roads,region]);const active=data.incidents.find(i=>i.id===selected)??incidents[0]??data.incidents[0];
 const conditions=useMemo(()=>{const names=["Bare & dry","Wet / slushy","Snow covered","Icy","Other"];return names.map((name,i)=>({name,value:roads.filter(r=>conditionGroup(r.condition)===name).length,color:["#4dca87","#54b3ff","#dcecff","#ff6b5e","#9da8b3"][i]}))},[roads]);
 const regions=useMemo(()=>["Central","Eastern","Northeastern","Northwestern","Southwestern"].map(name=>({name,incidents:data.incidents.filter(i=>i.region.toLowerCase().includes(name.toLowerCase())).length,adverse:data.roads.filter(r=>r.region.toLowerCase().includes(name.toLowerCase())&&conditionGroup(r.condition)!=="Bare & dry").length})),[data]);
 const adverse=roads.filter(r=>conditionGroup(r.condition)!=="Bare & dry").length;const poor=roads.filter(r=>/poor|nil/i.test(r.visibility)).length;const closure=incidents.filter(i=>/clos|block/i.test(`${i.type} ${i.description}`)).length;const readiness=Math.max(0,Math.min(100,Math.round(100-(incidents.length*1.1+adverse*.45+poor*1.5))));
 const plotIncidents=incidents.filter(i=>i.lon!=null&&i.lat!=null);const plotWeather=data.weather.filter(w=>w.lon!=null&&w.lat!=null);const conditionTotal=conditions.reduce((s,c)=>s+c.value,0);
 return <main className="shell"><header><div className="brand"><div className="route-mark"><Route/></div><div><span>ONTARIO TRAVEL NETWORK</span><h1>Roads <em>&</em> Weather</h1></div></div><div className="head-actions"><div className={`live ${status}`}><i/>{status==="live"?"LIVE DATA":status==="loading"?"SYNCING":"DEMO SNAPSHOT"}</div><button onClick={load} aria-label="Refresh travel data"><RefreshCw size={17} className={refreshing?"spin":""}/></button></div></header>
 <div className="controls"><Tabs value={view} onValueChange={setView}><TabsList className="view-tabs"><TabsTrigger value="network">Network overview</TabsTrigger><TabsTrigger value="incidents">Incidents</TabsTrigger><TabsTrigger value="conditions">Road conditions</TabsTrigger><TabsTrigger value="weather">Weather</TabsTrigger></TabsList></Tabs><div className="region"><span>REGION</span><Select value={region} onValueChange={setRegion}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All Ontario">All Ontario</SelectItem>{["Central","Eastern","Northeastern","Northwestern","Southwestern"].map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></div></div>
 <section className="kpis"><Panel className="readiness"><div><span>TRAVEL READINESS</span><ShieldCheck/></div><strong>{readiness}<b>/100</b></strong><small>based on current network reports</small><i style={{width:`${readiness}%`}}/></Panel>{[["ACTIVE INCIDENTS",incidents.length,"reported events",TrafficCone],["LANE CLOSURES",closure,"closure indicators",Car],["ADVERSE SURFACES",adverse,"non-dry segments",Snowflake],["LOW VISIBILITY",poor,"reported segments",Eye]].map(([l,v,n,Icon])=><Panel className="kpi" key={String(l)}><div><span>{l as string}</span><Icon size={18}/></div><strong>{Number(v).toLocaleString()}</strong><small>{n as string}</small></Panel>)}</section>
 <section className="grid"><Panel className="network"><div className="panel-head"><div><span>PROVINCIAL FIELD</span><h2>Incidents & weather stations</h2></div><div className="legend"><span><i/>Road event</span><span><i/>Weather city</span></div></div><div className="network-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:12,right:15,bottom:2,left:-8}}><CartesianGrid stroke="#283744" strokeDasharray="2 5"/><XAxis type="number" dataKey="lon" domain={[-95,-74]} ticks={[-94,-90,-86,-82,-78,-74]} tickFormatter={v=>`${Math.abs(v)}°W`} axisLine={false} tickLine={false} tick={{fill:"#718493",fontSize:11}}/><YAxis type="number" dataKey="lat" domain={[41,57]} ticks={[42,45,48,51,54,57]} tickFormatter={v=>`${v}°N`} axisLine={false} tickLine={false} tick={{fill:"#718493",fontSize:11}}/><ZAxis dataKey="severity" range={[55,160]}/><ChartTooltip content={<Tip/>} cursor={{stroke:"#748592",strokeDasharray:"3 3"}}/><Scatter data={plotIncidents} onClick={p=>setSelected(p.id)}>{plotIncidents.map(i=><Cell key={i.id} fill={color(i.region)} stroke={i.id===active?.id?"#fff":"transparent"} strokeWidth={2}/>)}</Scatter><Scatter data={plotWeather} shape="triangle" fill="#fff" fillOpacity={.85}/></ScatterChart></ResponsiveContainer></div><div className="network-foot"><span>{plotIncidents.length} positioned events</span><span>{plotWeather.length} reporting cities</span></div></Panel>
 <Panel className="incident-focus"><div className="focus-head"><div className="road-badge">{active?.road}</div><div><span>SELECTED INCIDENT</span><h2>{active?.type}</h2></div></div><h3>{active?.location}</h3><p>{active?.description}</p><div className="focus-grid"><div><span>DIRECTION</span><strong>{active?.direction||"Not specified"}</strong></div><div><span>LANES</span><strong>{active?.lanes||"Not specified"}</strong></div><div><span>REGION</span><strong>{active?.region}</strong></div><div><span>UPDATED</span><strong>{active?ago(active.updated):"—"}</strong></div></div><div className="severity"><span>REPORT STATUS</span><b className={(active?.severity??"").toLowerCase()}>{active?.severity}</b></div></Panel>
 <Panel className="condition-panel"><div className="panel-head"><div><span>SURFACE REPORTS</span><h2>Road condition mix</h2></div><span>{conditionTotal} segments</span></div><div className="donut-wrap"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={conditions} dataKey="value" innerRadius={54} outerRadius={76} paddingAngle={3} stroke="none">{conditions.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><ChartTooltip/></PieChart></ResponsiveContainer><div><strong>{conditionTotal}</strong><span>REPORTS</span></div></div><div className="condition-list">{conditions.map(c=><div key={c.name}><i style={{background:c.color}}/><span>{c.name}</span><b>{c.value}</b></div>)}</div></div></Panel>
 <Panel className="region-panel"><div className="panel-head"><div><span>REGIONAL LOAD</span><h2>Events & adverse roads</h2></div></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={regions}><CartesianGrid vertical={false} stroke="#e3e7e8" strokeDasharray="3 4"/><XAxis dataKey="name" tickFormatter={v=>v.slice(0,3)} axisLine={false} tickLine={false} tick={{fill:"#84929a",fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#84929a",fontSize:11}} width={25}/><ChartTooltip/><Bar dataKey="incidents" name="Incidents" fill="#182733" radius={[4,4,0,0]}/><Bar dataKey="adverse" name="Adverse roads" fill="#ffd83d" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Panel>
 <Panel className="weather"><div className="panel-head"><div><span>CITY WEATHER</span><h2>Current conditions</h2></div><CloudRain size={18}/></div><div className="weather-list">{data.weather.slice(0,7).map(w=><div key={w.id}><span><strong>{w.city}</strong><small>{w.condition}</small></span><b>{w.temp==null?"—":`${w.temp}°`}</b><span className="wind"><Wind size={13}/>{w.wind??"—"} km/h</span></div>)}</div></Panel>
 <Panel className="stream"><div className="panel-head"><div><span>TRAFFIC STREAM</span><h2>Latest road events</h2></div><Navigation size={18}/></div><div className="incident-list">{incidents.sort((a,b)=>b.updated-a.updated).slice(0,7).map(i=><button key={i.id} onClick={()=>setSelected(i.id)} className={i.id===active?.id?"active":""}><i style={{background:color(i.region)}}/><span><strong>Hwy {i.road} · {i.type}</strong><small>{i.location} · {ago(i.updated)}</small></span><ChevronRight size={16}/></button>)}</div></Panel></section>
 <footer><span>Road data: Ontario 511 · Weather: Environment and Climate Change Canada</span><span>Updated {new Date(data.updatedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></footer></main>
}
