"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip as ChartTooltip, XAxis, YAxis, ZAxis } from "recharts";
import { Activity, CalendarDays, ChevronRight, CircleDot, CloudLightning, Droplets, Flame, Globe2, Layers3, Mountain, Radio, RefreshCw, Satellite, Waves, Wind } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Geometry={date:string;type:string;coordinates:unknown;magnitudeValue?:number;magnitudeUnit?:string};
type RawEvent={id:string;title:string;description?:string|null;link:string;closed:string|null;categories:{id:string;title:string}[];sources:{id:string;url:string}[];geometry:Geometry[]};
type EventItem={id:string;title:string;description:string;category:string;categoryId:string;date:number;started:number;closed:number|null;lon:number;lat:number;magnitude:number|null;unit:string;sourceCount:number;observations:number;link:string};

const CATEGORY_COLORS:Record<string,string>={wildfires:"#f26a3d",severeStorms:"#6761e8",volcanoes:"#e24352",floods:"#348bc6",seaLakeIce:"#79bfd1",drought:"#d5a84a",dustHaze:"#b78768",landslides:"#8a725d",snow:"#aac8dc",tempExtremes:"#e9833e",waterColor:"#2bb09b",earthquakes:"#c95c78",manmade:"#757b84"};
const CATEGORY_ICONS:Record<string,React.ElementType>={wildfires:Flame,severeStorms:CloudLightning,volcanoes:Mountain,floods:Droplets,seaLakeIce:Waves,drought:Activity,dustHaze:Wind,landslides:Mountain,snow:Waves,tempExtremes:Activity,waterColor:Droplets,earthquakes:Activity};
const colorFor=(id:string)=>CATEGORY_COLORS[id]??"#77929e";
const dateText=(n:number)=>new Date(n).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});
const age=(n:number)=>{const d=Math.max(0,Math.floor((Date.now()-n)/86400000));return d===0?"Today":d===1?"1 day ago":`${d} days ago`};

function pointFromGeometry(g:Geometry|undefined):[number,number]{
  if(!g)return[0,0]; const c=g.coordinates as unknown;
  if(g.type==="Point"&&Array.isArray(c))return[Number(c[0])||0,Number(c[1])||0];
  let node:any=c; while(Array.isArray(node)&&Array.isArray(node[0]))node=node[0];
  return Array.isArray(node)?[Number(node[0])||0,Number(node[1])||0]:[0,0];
}
function normalize(raw:RawEvent):EventItem{const last=raw.geometry.at(-1);const first=raw.geometry[0];const[lon,lat]=pointFromGeometry(last);return{id:raw.id,title:raw.title,description:raw.description??"",category:raw.categories[0]?.title??"Other",categoryId:raw.categories[0]?.id??"other",date:new Date(last?.date??Date.now()).getTime(),started:new Date(first?.date??Date.now()).getTime(),closed:raw.closed?new Date(raw.closed).getTime():null,lon,lat,magnitude:last?.magnitudeValue??null,unit:last?.magnitudeUnit??"",sourceCount:raw.sources.length,observations:raw.geometry.length,link:raw.link};}
function fallback():EventItem[]{const seed=[
  ["Wildfires","wildfires",-118,53],["Severe Storms","severeStorms",128,22],["Volcanoes","volcanoes",122,-8],["Floods","floods",90,24],["Sea and Lake Ice","seaLakeIce",-40,74],["Drought","drought",18,-25],["Dust and Haze","dustHaze",45,25],["Landslides","landslides",84,28]
] as const;return Array.from({length:38},(_,i)=>{const s=seed[i%seed.length];return{id:`demo-${i}`,title:`${s[0]} event ${String(i+1).padStart(2,"0")}`,description:"",category:s[0],categoryId:s[1],date:Date.now()-((i*37)%2100)*3600000,started:Date.now()-((i*61)%2150)*3600000,closed:i%4===0?Date.now()-i*3600000:null,lon:s[2]+((i*13)%28)-14,lat:s[3]+((i*7)%18)-9,magnitude:i%3===0?20+i*1.4:null,unit:i%3===0?"acres":"",sourceCount:1+i%3,observations:1+i%9,link:""};});}
function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}>{children}</section>}
function Tip({active,payload,label}:{active?:boolean;payload?:Array<{payload:EventItem&{name?:string;value?:number;count?:number};name:string;value:number}>;label?:string}){if(!active||!payload?.length)return null;const d=payload[0].payload;return <div className="tip"><strong>{d.title??d.name??label}</strong>{d.category&&<span>{d.category} · {age(d.date)}</span>}{d.value!=null&&<span>{d.value} events</span>}</div>}

export default function Home(){
  const[events,setEvents]=useState<EventItem[]>(fallback);const[status,setStatus]=useState<"loading"|"live"|"snapshot">("loading");const[category,setCategory]=useState("all");const[stateFilter,setStateFilter]=useState("all");const[selected,setSelected]=useState("");const[refreshing,setRefreshing]=useState(false);const[updated,setUpdated]=useState(Date.now());
  const load=useCallback(async()=>{setRefreshing(true);try{const r=await fetch("/api/events",{cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json();const rows=(data.events as RawEvent[]).map(normalize);if(!rows.length)throw new Error();setEvents(rows);setStatus("live");setUpdated(Date.now());if(!selected)setSelected(rows[0].id)}catch{setStatus("snapshot");setUpdated(Date.now())}finally{setRefreshing(false)}},[selected]);
  useEffect(()=>{load()},[]);
  const categories=useMemo(()=>{const map=new Map<string,{id:string,title:string,count:number}>();events.forEach(e=>{const x=map.get(e.categoryId);map.set(e.categoryId,{id:e.categoryId,title:e.category,count:(x?.count??0)+1})});return[...map.values()].sort((a,b)=>b.count-a.count)},[events]);
  const filtered=useMemo(()=>events.filter(e=>(category==="all"||e.categoryId===category)&&(stateFilter==="all"||(stateFilter==="open"?!e.closed:!!e.closed))),[events,category,stateFilter]);
  const active=events.find(e=>e.id===selected)??filtered[0]??events[0];
  const stats=useMemo(()=>({tracked:filtered.length,open:filtered.filter(e=>!e.closed).length,recent:filtered.filter(e=>Date.now()-e.date<7*86400000).length,sources:filtered.reduce((s,e)=>s+e.sourceCount,0)}),[filtered]);
  const timeline=useMemo(()=>Array.from({length:12},(_,i)=>{const end=Date.now()-(11-i)*7*86400000;const start=end-7*86400000;return{name:new Date(end).toLocaleDateString(undefined,{month:"short",day:"numeric"}),value:events.filter(e=>e.started>=start&&e.started<end).length}}),[events]);
  const breakdown=useMemo(()=>categories.slice(0,7).map(c=>({name:c.title,value:c.count,id:c.id,color:colorFor(c.id)})),[categories]);
  const sourceRanks=useMemo(()=>categories.slice(0,6).map(c=>({name:c.title,value:c.count,id:c.id})).reverse(),[categories]);
  const field=useMemo(()=>filtered.filter(e=>Number.isFinite(e.lon)&&Number.isFinite(e.lat)),[filtered]);
  const activeColor=colorFor(active?.categoryId??"");const ActiveIcon=CATEGORY_ICONS[active?.categoryId]??CircleDot;
  return <main className="shell">
    <header><div className="brand"><div className="brand-icon"><Globe2/></div><div><span>EARTH SYSTEM MONITOR</span><h1>Natural Events <em>Atlas</em></h1></div></div><div className="head-actions"><div className={`live-badge ${status}`}><Radio size={15}/>{status==="live"?"LIVE EONET DATA":status==="loading"?"CONNECTING":"DEMO SNAPSHOT"}</div><button onClick={load} aria-label="Refresh data"><RefreshCw size={17} className={refreshing?"spin":""}/></button></div></header>
    <div className="control-bar"><Tabs value={category} onValueChange={setCategory}><TabsList className="category-tabs"><TabsTrigger value="all">All events</TabsTrigger>{categories.slice(0,5).map(c=><TabsTrigger value={c.id} key={c.id}>{c.title}<b>{c.count}</b></TabsTrigger>)}</TabsList></Tabs><div className="state-picker"><span>STATUS</span><Select value={stateFilter} onValueChange={setStateFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All records</SelectItem><SelectItem value="open">Open events</SelectItem><SelectItem value="closed">Closed events</SelectItem></SelectContent></Select></div></div>
    <section className="kpis">{[["EVENTS TRACKED",stats.tracked,"in current view",Satellite],["OPEN NOW",stats.open,"actively monitored",Activity],["UPDATED THIS WEEK",stats.recent,"fresh observations",CalendarDays],["SOURCE LINKS",stats.sources,"supporting records",Layers3]].map(([label,value,note,Icon],i)=><Panel className="kpi" key={String(label)}><div><span>{label as string}</span><Icon size={18}/></div><strong>{Number(value).toLocaleString()}</strong><small>{note as string}</small><i style={{background:["#1d3f54","#f26a3d","#2bb09b","#6761e8"][i]}}/></Panel>)}</section>
    <section className="grid">
      <Panel className="atlas"><div className="panel-head"><div><span>GEOSPATIAL VIEW</span><h2>Event observation field</h2></div><div className="field-key"><span><i/>Active</span><span><i/>Closed</span></div></div><div className="atlas-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:14,right:15,bottom:2,left:-8}}><CartesianGrid stroke="#315064" strokeDasharray="2 5"/><XAxis type="number" dataKey="lon" domain={[-180,180]} ticks={[-180,-120,-60,0,60,120,180]} tickFormatter={v=>`${Math.abs(v)}°${v<0?"W":"E"}`} axisLine={false} tickLine={false} tick={{fill:"#668399",fontSize:11}}/><YAxis type="number" dataKey="lat" domain={[-90,90]} ticks={[-60,-30,0,30,60]} tickFormatter={v=>`${Math.abs(v)}°${v<0?"S":"N"}`} axisLine={false} tickLine={false} tick={{fill:"#668399",fontSize:11}}/><ZAxis dataKey="observations" range={[40,320]}/><ChartTooltip content={<Tip/>} cursor={{stroke:"#557386",strokeDasharray:"3 3"}}/><Scatter data={field} onClick={p=>setSelected(p.id)}>{field.map(e=><Cell key={e.id} fill={colorFor(e.categoryId)} fillOpacity={e.closed?.55:.92} stroke={e.id===active?.id?"#fff":"transparent"} strokeWidth={2}/>)}</Scatter></ScatterChart></ResponsiveContainer></div><div className="atlas-foot"><span>Each point shows the latest available event geometry</span><span>{field.length} plotted</span></div></Panel>
      <Panel className="focus"><div className="focus-top"><div className="focus-icon" style={{background:activeColor}}><ActiveIcon size={24}/></div><div><span>SELECTED EVENT</span><h2>{active?.title}</h2></div></div><div className="focus-meta"><span style={{color:activeColor}}>{active?.category}</span><span>{active?.closed?"Closed":"Open"}</span></div><div className="focus-stats"><div><span>LATEST OBSERVATION</span><strong>{active?dateText(active.date):"—"}</strong></div><div><span>OBSERVATIONS</span><strong>{active?.observations}</strong></div><div><span>SOURCES</span><strong>{active?.sourceCount}</strong></div><div><span>COORDINATES</span><strong>{active?.lat.toFixed(1)}°, {active?.lon.toFixed(1)}°</strong></div></div>{active?.magnitude!=null&&<div className="magnitude"><span>REPORTED MAGNITUDE</span><strong>{active.magnitude.toLocaleString()} {active.unit}</strong></div>}<div className="focus-track"><div style={{width:`${Math.min(100,(active?.observations??1)*8)}%`,background:activeColor}}/></div><small>Tracking since {active?dateText(active.started):"—"}</small></Panel>
      <Panel className="timeline"><div className="panel-head"><div><span>EVENT VELOCITY</span><h2>New records by week</h2></div><span>90 days</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline} margin={{top:12,right:8,left:-22,bottom:0}}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2bb09b" stopOpacity=".36"/><stop offset="1" stopColor="#2bb09b" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e4e7e8" strokeDasharray="3 4"/><XAxis dataKey="name" axisLine={false} tickLine={false} interval={2} tick={{fill:"#8c969c",fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#8c969c",fontSize:11}}/><ChartTooltip/><Area type="monotone" dataKey="value" stroke="#2bb09b" strokeWidth={2.5} fill="url(#area)"/></AreaChart></ResponsiveContainer></div></Panel>
      <Panel className="mix"><div className="panel-head"><div><span>EVENT MIX</span><h2>Category share</h2></div></div><div className="mix-body"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={breakdown} dataKey="value" innerRadius={54} outerRadius={78} paddingAngle={3} stroke="none">{breakdown.map(d=><Cell key={d.id} fill={d.color}/>)}</Pie><ChartTooltip/></PieChart></ResponsiveContainer><div><strong>{events.length}</strong><span>TOTAL</span></div></div><div className="legend-list">{breakdown.slice(0,5).map(d=><button onClick={()=>setCategory(d.id)} key={d.id}><i style={{background:d.color}}/><span>{d.name}</span><b>{d.value}</b></button>)}</div></div></Panel>
      <Panel className="ranking"><div className="panel-head"><div><span>CATEGORY VOLUME</span><h2>Most monitored</h2></div></div><div className="rank-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={sourceRanks} layout="vertical" margin={{left:10,right:22}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={105} axisLine={false} tickLine={false} tick={{fill:"#53646d",fontSize:11}}/><ChartTooltip/><Bar dataKey="value" radius={[0,6,6,0]} barSize={13}>{sourceRanks.map(d=><Cell key={d.id} fill={colorFor(d.id)}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>
      <Panel className="stream"><div className="panel-head"><div><span>RECENT ACTIVITY</span><h2>Latest observations</h2></div><Radio size={17}/></div><div className="event-list">{filtered.sort((a,b)=>b.date-a.date).slice(0,8).map(e=><button key={e.id} onClick={()=>setSelected(e.id)} className={e.id===active?.id?"active":""}><i style={{background:colorFor(e.categoryId)}}/><span><strong>{e.title}</strong><small>{e.category} · {age(e.date)}</small></span><ChevronRight size={16}/></button>)}</div></Panel>
    </section>
    <footer><span>Natural event metadata: NASA Earth Observatory Natural Event Tracker (EONET)</span><span>Refreshed {new Date(updated).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></footer>
  </main>
}
