"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,ComposedChart,Line,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {BadgeDollarSign,BriefcaseBusiness,CalendarDays,ChartNoAxesCombined,Landmark,Leaf,RefreshCw,ShieldCheck,TrendingDown,TrendingUp} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
type Point={date:string;label:string;value:number};type Data={statcan:Record<string,Point[]>;boc:Record<string,Point[]>;fetchedAt:string};
const make=(base:number,slope:number,wave:number)=>Array.from({length:48},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(47-i));return{date:d.toISOString().slice(0,10),label:d.toLocaleDateString("en-CA",{month:"short",year:"2-digit"}),value:base+i*slope+Math.sin(i/3)*wave}});
const fallback:Data={fetchedAt:new Date().toISOString(),statcan:{employment:make(20600,22,75),participation:make(65,-.008,.12),unemployment:make(6.1,.008,.24),cpi:make(158,.25,.3),gdp:make(2280000,2100,6000)},boc:{V39079:make(2.25,0,0),FXUSDCAD:make(1.35,.0008,.025),"BD.CDN.2YR.DQ.YLD":make(2.42,-.002,.12),"BD.CDN.5YR.DQ.YLD":make(2.55,-.001,.1),"BD.CDN.10YR.DQ.YLD":make(2.85,0,.09),"BD.CDN.LONG.DQ.YLD":make(3.15,.001,.07)}};
const last=(s?:Point[])=>s?.at(-1)?.value||0;const change=(s?:Point[],period=1)=>{const c=s?.at(-1)?.value,p=s?.at(-(period+1))?.value;return c!=null&&p!=null&&p?(c-p)/p*100:0};const signed=(n:number,d=1)=>`${n>=0?"+":""}${n.toFixed(d)}%`;
function Delta({value,good=true}:{value:number;good?:boolean}){const up=value>=0,positive=good?up:!up;return <span className={`delta ${positive?"good":"bad"}`}>{up?<TrendingUp/>:<TrendingDown/>}{signed(value)}</span>}
function Tip({active,payload,label,suffix="",decimals=2}:any){if(!active||!payload?.length)return null;return <div className="tip"><b>{label}</b>{payload.map((p:any)=><div key={p.dataKey}><i style={{background:p.color}}/><span>{p.name}</span><strong>{Number(p.value).toLocaleString("en-CA",{maximumFractionDigits:decimals})}{suffix}</strong></div>)}</div>}
export default function Home(){
 const[data,setData]=useState<Data>(fallback),[live,setLive]=useState(false),[loading,setLoading]=useState(true),[macro,setMacro]=useState("gdp");
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/economy",{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json());setLive(true)}catch{setData(fallback);setLive(false)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const s=data.statcan,b=data.boc,cpi=last(s.cpi),inflation=change(s.cpi,12),unemployment=last(s.unemployment),participation=last(s.participation),employment=last(s.employment),gdp=last(s.gdp),policy=last(b.V39079),cad=last(b.FXUSDCAD);
 const macroData=useMemo(()=>{const series=s[macro]||[];if(macro==="cpi")return series.slice(-48).map((p,i,a)=>({...p,value:i>=12&&a[i-12].value?(p.value-a[i-12].value)/a[i-12].value*100:null})).filter(p=>p.value!=null);return series.slice(-48)},[s,macro]);
 const rateTrend=useMemo(()=>{const policyMap=new Map((b.V39079||[]).map(p=>[p.date,p.value]));return (b["BD.CDN.10YR.DQ.YLD"]||[]).slice(-260).map(p=>({...p,tenYear:p.value,policy:policyMap.get(p.date)}))},[b]);
 const fx=(b.FXUSDCAD||[]).slice(-260);const curve=[{term:"2Y",yield:last(b["BD.CDN.2YR.DQ.YLD"])},{term:"5Y",yield:last(b["BD.CDN.5YR.DQ.YLD"])},{term:"10Y",yield:last(b["BD.CDN.10YR.DQ.YLD"])},{term:"Long",yield:last(b["BD.CDN.LONG.DQ.YLD"])}];
 const macroConfig:{[k:string]:{title:string;suffix:string;decimals:number}}={gdp:{title:"Real GDP",suffix:"M",decimals:0},cpi:{title:"Inflation",suffix:"%",decimals:2},employment:{title:"Employment",suffix:"K",decimals:0},unemployment:{title:"Unemployment",suffix:"%",decimals:2}};const cfg=macroConfig[macro];
 const signals=[{label:"Growth pulse",value:change(s.gdp),text:change(s.gdp)>=0?"Expanding":"Contracting",tone:change(s.gdp)>=0?"green":"red"},{label:"Price pressure",value:inflation,text:inflation>3?"Elevated":inflation<1?"Soft":"In range",tone:inflation>3?"red":"green"},{label:"Labour market",value:change(s.employment),text:change(s.employment)>=0?"Adding jobs":"Cooling",tone:change(s.employment)>=0?"green":"amber"},{label:"Canadian dollar",value:-change(fx,20),text:change(fx,20)<=0?"Strengthening":"Weakening",tone:change(fx,20)<=0?"green":"amber"}];
 return <main><header><div className="brand"><div className="brandmark"><Leaf/></div><div><b>Canada Economy</b><span>NATIONAL DATA DASHBOARD</span></div></div><div className="header-actions"><span className={`live ${live?"":"demo"}`}><i/>{live?"LIVE PUBLIC DATA":"DEMO SNAPSHOT"}</span><button onClick={load} disabled={loading} aria-label="Refresh dashboard"><RefreshCw className={loading?"spin":""}/></button></div></header>
 <div className="dashboard"><section className="title-row"><div><p>CANADIAN ECONOMIC MONITOR</p><h1>The economy, <em>on one screen.</em></h1></div><div className="updated"><CalendarDays/><span>UPDATED<br/><b>{new Date(data.fetchedAt).toLocaleString("en-CA",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</b></span></div></section>
 <section className="kpis"><Kpi icon={<ChartNoAxesCombined/>} label="Real GDP" value={`$${(gdp/1e6).toFixed(2)}T`} note="Chained 2017 dollars" delta={change(s.gdp)}/><Kpi icon={<BadgeDollarSign/>} label="Inflation" value={`${inflation.toFixed(1)}%`} note={`CPI index ${cpi.toFixed(1)}`} delta={inflation-2} good={false}/><Kpi icon={<BriefcaseBusiness/>} label="Unemployment" value={`${unemployment.toFixed(1)}%`} note={`${(employment/1000).toFixed(2)}M employed`} delta={change(s.unemployment)} good={false}/><Kpi icon={<Landmark/>} label="Policy rate" value={`${policy.toFixed(2)}%`} note={`USD/CAD ${cad.toFixed(4)}`} delta={change(b.V39079)}/></section>
 <section className="signal-strip">{signals.map(item=><div key={item.label}><span className={`signal-dot ${item.tone}`}/><p>{item.label}<b>{item.text}</b></p><Delta value={item.value}/></div>)}</section>
 <section className="main-grid"><article className="panel macro-panel"><PanelHead title={cfg.title} subtitle="Statistics Canada monthly series" extra={<Tabs value={macro} onValueChange={setMacro}><TabsList className="macro-tabs"><TabsTrigger value="gdp">GDP</TabsTrigger><TabsTrigger value="cpi">Inflation</TabsTrigger><TabsTrigger value="employment">Jobs</TabsTrigger><TabsTrigger value="unemployment">Unemployment</TabsTrigger></TabsList></Tabs>}/><div className="macro-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={macroData} margin={{top:20,right:18,left:0,bottom:0}}><defs><linearGradient id="redFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e31837" stopOpacity={.32}/><stop offset="1" stopColor="#e31837" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e4e8ed" vertical={false} strokeDasharray="4 5"/><XAxis dataKey="label" interval={5} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:12}}/><YAxis tickFormatter={v=>macro==="gdp"?`${(v/1e6).toFixed(2)}T`:macro==="employment"?`${(v/1000).toFixed(1)}M`:`${v}%`} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:12}} width={58}/><Tooltip content={<Tip suffix={cfg.suffix} decimals={cfg.decimals}/>}/>{macro==="cpi"&&<ReferenceLine y={2} stroke="#2f855a" strokeDasharray="5 5" label={{value:"2% target",fill:"#2f855a",fontSize:11}}/>}<Area type="monotone" dataKey="value" name={cfg.title} stroke="#e31837" strokeWidth={2.6} fill="url(#redFill)"/></AreaChart></ResponsiveContainer></div></article>
 <article className="panel labour"><PanelHead title="Labour force" subtitle="Participation and employment conditions"/><div className="labour-ring"><div className="ring" style={{"--pct":`${participation*3.6}deg`} as React.CSSProperties}><div><b>{participation.toFixed(1)}%</b><span>PARTICIPATION</span></div></div></div><div className="labour-stats"><div><span>Employed</span><b>{(employment/1000).toFixed(2)}M</b><Delta value={change(s.employment)}/></div><div><span>Unemployed rate</span><b>{unemployment.toFixed(1)}%</b><Delta value={change(s.unemployment)} good={false}/></div></div></article></section>
 <section className="lower-grid"><article className="panel"><PanelHead title="Interest-rate path" subtitle="Policy rate versus 10-year government yield" extra={<div className="legend"><span><i className="red"/>Policy</span><span><i className="navy"/>10-year</span></div>}/><div className="rate-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rateTrend} margin={{top:18,right:16,left:0,bottom:0}}><CartesianGrid stroke="#e4e8ed" vertical={false} strokeDasharray="4 5"/><XAxis dataKey="label" interval={45} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:11}}/><YAxis tickFormatter={v=>`${v}%`} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:11}} width={44}/><Tooltip content={<Tip suffix="%"/>}/><Line type="stepAfter" dataKey="policy" name="Policy rate" stroke="#e31837" strokeWidth={2.3} dot={false} connectNulls/><Line type="monotone" dataKey="tenYear" name="10-year yield" stroke="#173b5c" strokeWidth={2.3} dot={false}/></ComposedChart></ResponsiveContainer></div></article>
 <article className="panel"><PanelHead title="Yield curve" subtitle="Government of Canada benchmark bonds"/><div className="curve-value"><span>10-YEAR</span><b>{curve[2].yield.toFixed(2)}%</b></div><div className="curve-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={curve} margin={{top:12,right:8,left:-15,bottom:0}}><CartesianGrid stroke="#e4e8ed" vertical={false} strokeDasharray="4 5"/><XAxis dataKey="term" axisLine={false} tickLine={false} tick={{fill:"#566574",fontSize:12}}/><YAxis domain={["dataMin - .3","dataMax + .3"]} tickFormatter={v=>`${v}%`} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:11}}/><Tooltip content={<Tip suffix="%"/>}/><Bar dataKey="yield" name="Yield" fill="#173b5c" radius={[6,6,0,0]} barSize={27}/></BarChart></ResponsiveContainer></div></article>
 <article className="panel"><PanelHead title="Canadian dollar" subtitle="Canadian dollars per U.S. dollar"/><div className="curve-value"><span>USD / CAD</span><b>{cad.toFixed(4)}</b></div><div className="curve-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={fx} margin={{top:12,right:8,left:-8,bottom:0}}><defs><linearGradient id="cadFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d4a72c" stopOpacity={.35}/><stop offset="1" stopColor="#d4a72c" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e4e8ed" vertical={false} strokeDasharray="4 5"/><XAxis dataKey="label" interval={45} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:11}}/><YAxis domain={["dataMin - .02","dataMax + .02"]} tickFormatter={v=>v.toFixed(2)} axisLine={false} tickLine={false} tick={{fill:"#788697",fontSize:11}} width={42}/><Tooltip content={<Tip decimals={4}/>}/><Area type="monotone" dataKey="value" name="USD/CAD" stroke="#c39012" strokeWidth={2.2} fill="url(#cadFill)"/></AreaChart></ResponsiveContainer></div></article></section>
 <footer><span><ShieldCheck/> Statistics Canada + Bank of Canada official public data</span><span>Values may be revised after release</span></footer></div></main>
}
function Kpi({icon,label,value,note,delta,good=true}:{icon:React.ReactNode;label:string;value:string;note:string;delta:number;good?:boolean}){return <article className="kpi"><div className="kpi-icon">{icon}</div><div><span>{label}</span><b>{value}</b><small>{note}</small></div><Delta value={delta} good={good}/></article>}
function PanelHead({title,subtitle,extra}:{title:string;subtitle:string;extra?:React.ReactNode}){return <div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div>{extra}</div>}
