"use client";

import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip as ChartTooltip, XAxis, YAxis, ZAxis } from "recharts";
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, CircleDollarSign, Globe2, RefreshCw, Sparkles, Users } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Point = { year: number; value: number };
type Metrics = Record<string, Point[]>;
type Country = { code: string; iso2: string; name: string; region: string; income: string; capital: string; metrics: Metrics };

const COLORS = ["#54e7c2", "#7c8cff", "#f6c768", "#ff7da8", "#50b6ff", "#bc8cff"];
const METRIC_META: Record<string, { label: string; color: string }> = {
  gdp: { label: "GDP", color: "#54e7c2" }, gdpPerCapita: { label: "GDP / person", color: "#7c8cff" }, growth: { label: "GDP growth", color: "#f6c768" }, inflation: { label: "Inflation", color: "#ff7da8" }, unemployment: { label: "Unemployment", color: "#50b6ff" },
};

const seeds = [
  ["USA", "US", "United States", "North America", "High income", 29100, 340, 2.8, 3.2, 4.0, 29], ["CHN", "CN", "China", "East Asia & Pacific", "Upper middle income", 18800, 1410, 5.0, 0.4, 5.2, 37], ["DEU", "DE", "Germany", "Europe & Central Asia", "High income", 4700, 84, 0.2, 2.5, 3.2, 88], ["JPN", "JP", "Japan", "East Asia & Pacific", "High income", 4070, 124, 0.9, 2.7, 2.6, 47], ["IND", "IN", "India", "South Asia", "Lower middle income", 3940, 1450, 6.5, 4.8, 4.2, 46], ["GBR", "GB", "United Kingdom", "Europe & Central Asia", "High income", 3690, 69, 1.1, 2.6, 4.4, 64], ["FRA", "FR", "France", "Europe & Central Asia", "High income", 3170, 68, 0.8, 2.1, 7.4, 64], ["ITA", "IT", "Italy", "Europe & Central Asia", "High income", 2380, 59, 0.6, 1.2, 5.8, 67], ["CAN", "CA", "Canada", "North America", "High income", 2240, 41, 1.5, 2.4, 6.6, 66], ["BRA", "BR", "Brazil", "Latin America & Caribbean", "Upper middle income", 2180, 212, 2.3, 4.4, 6.5, 34], ["RUS", "RU", "Russian Federation", "Europe & Central Asia", "Upper middle income", 2160, 144, 3.6, 8.4, 2.4, 49], ["KOR", "KR", "Korea, Rep.", "East Asia & Pacific", "High income", 1870, 52, 2.2, 2.3, 2.8, 87], ["AUS", "AU", "Australia", "East Asia & Pacific", "High income", 1800, 27, 1.8, 3.0, 4.1, 45], ["MEX", "MX", "Mexico", "Latin America & Caribbean", "Upper middle income", 1790, 131, 1.4, 4.5, 2.8, 74], ["IDN", "ID", "Indonesia", "East Asia & Pacific", "Upper middle income", 1470, 283, 5.0, 2.2, 4.9, 43], ["TUR", "TR", "Türkiye", "Europe & Central Asia", "Upper middle income", 1320, 87, 3.2, 44.4, 8.7, 69], ["SAU", "SA", "Saudi Arabia", "Middle East & North Africa", "High income", 1100, 34, 1.3, 1.9, 4.4, 63], ["ZAF", "ZA", "South Africa", "Sub-Saharan Africa", "Upper middle income", 410, 64, 1.0, 4.5, 32.1, 65],
] as const;

function makeFallback(): Country[] {
  return seeds.map(([code, iso2, name, region, income, gdpB, popM, growth, inflation, unemployment, trade], index) => {
    const metrics: Metrics = {};
    const vals = { gdp: gdpB * 1e9, population: popM * 1e6, growth, inflation, unemployment, trade, gdpPerCapita: (gdpB * 1e9) / (popM * 1e6) };
    for (const [key, value] of Object.entries(vals)) metrics[key] = Array.from({ length: 7 }, (_, i) => ({ year: 2018 + i, value: Number(value) * ((key === "gdp" || key === "gdpPerCapita" || key === "population") ? .78 + i * .037 : 1 + Math.sin(index + i * .9) * .16) }));
    return { code, iso2, name, region, income, capital: "—", metrics };
  });
}

const latest = (country: Country | undefined, key: string) => country?.metrics[key]?.at(-1)?.value ?? null;
const fmtMoney = (n: number | null, compact = true) => n == null ? "—" : new Intl.NumberFormat("en", { style: "currency", currency: "USD", notation: compact ? "compact" : "standard", maximumFractionDigits: compact ? 2 : 0 }).format(n);
const fmtNum = (n: number | null) => n == null ? "—" : new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 2 }).format(n);
const fmtPct = (n: number | null) => n == null ? "—" : `${n.toFixed(1)}%`;
const broadRegion = (region: string) => /Latin|North America/i.test(region) ? "Americas" : /Europe/i.test(region) ? "Europe" : /Africa/i.test(region) ? "Africa" : /East Asia|South Asia/i.test(region) ? "Asia" : /Middle East/i.test(region) ? "Middle East" : "Oceania";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section>; }
function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; name: string; payload?: { name?: string } }>; label?: string | number }) {
  if (!active || !payload?.length) return null;
  return <div className="chart-tip"><strong>{payload[0]?.payload?.name ?? label}</strong>{payload.map((item, i) => <span key={`${item.name}-${i}`}><i style={{ background: COLORS[i % COLORS.length] }} />{item.name}: {typeof item.value === "number" ? item.value.toLocaleString(undefined, { maximumFractionDigits: 1 }) : item.value}</span>)}</div>;
}

export default function Home() {
  const [countries, setCountries] = useState<Country[]>(() => makeFallback());
  const [selected, setSelected] = useState("CAN"); const [region, setRegion] = useState("World"); const [metric, setMetric] = useState("gdp");
  const [status, setStatus] = useState<"loading" | "live" | "snapshot">("loading"); const [updatedAt, setUpdatedAt] = useState(""); const [spin, setSpin] = useState(false);
  const load = async () => { setSpin(true); try { const response = await fetch("/api/world", { cache: "no-store" }); if (!response.ok) throw new Error(); const payload = await response.json(); if (!payload.countries?.length) throw new Error(); setCountries(payload.countries); setUpdatedAt(payload.updatedAt); setStatus("live"); } catch { setStatus("snapshot"); setUpdatedAt(new Date().toISOString()); } finally { setSpin(false); } };
  useEffect(() => { load(); }, []);

  const visible = useMemo(() => region === "World" ? countries : countries.filter((c) => broadRegion(c.region) === region), [countries, region]);
  const active = countries.find((c) => c.code === selected) ?? countries[0];
  const world = useMemo(() => { const complete = visible.filter((c) => latest(c, "gdp") && latest(c, "population")); const totalGdp = complete.reduce((s, c) => s + (latest(c, "gdp") ?? 0), 0); const totalPop = complete.reduce((s, c) => s + (latest(c, "population") ?? 0), 0); const growth = totalGdp ? complete.reduce((s, c) => s + (latest(c, "growth") ?? 0) * (latest(c, "gdp") ?? 0), 0) / totalGdp : 0; const values = complete.map((c) => latest(c, "inflation") ?? 0).sort((a,b) => a-b); return { totalGdp, totalPop, growth, inflation: values[Math.floor(values.length / 2)] ?? 0 }; }, [visible]);
  const top = useMemo(() => [...visible].sort((a, b) => (latest(b, "gdp") ?? 0) - (latest(a, "gdp") ?? 0)).slice(0, 8).reverse().map((c) => ({ name: c.name, value: (latest(c, "gdp") ?? 0) / 1e12, code: c.code })), [visible]);
  const scatter = useMemo(() => visible.map((c) => ({ name: c.name, code: c.code, x: (latest(c, "gdpPerCapita") ?? 0) / 1000, y: latest(c, "growth") ?? 0, z: Math.max(8, Math.sqrt((latest(c, "population") ?? 0) / 1e6) * 7) })).filter((d) => d.x > 0), [visible]);
  const trend = useMemo(() => (active?.metrics[metric] ?? []).map((p) => ({ year: p.year, value: metric === "gdp" ? p.value / 1e12 : metric === "gdpPerCapita" ? p.value / 1000 : p.value })), [active, metric]);
  const pulse = useMemo(() => [...countries].sort((a,b) => (latest(b, "gdp") ?? 0) - (latest(a, "gdp") ?? 0)).slice(0, 7), [countries]);
  const selectRegion = (value: string) => { setRegion(value); if (value !== "World" && broadRegion(active.region) !== value) { const first = countries.find((c) => broadRegion(c.region) === value); if (first) setSelected(first.code); } };

  return <main className="dashboard-shell">
    <aside className="rail"><div className="brand-mark"><Globe2 size={22} /></div><div className="rail-line" />{["G","L","O","B","E"].map((x)=><span key={x}>{x}</span>)}<div className="rail-line bottom" /><small>WB</small></aside>
    <div className="dashboard">
      <header className="topbar"><div><div className="eyebrow"><Sparkles size={13} /> Global data terminal</div><h1>World Economy <em>Explorer</em></h1></div><div className="top-actions"><div className={`status ${status}`}><span />{status === "live" ? "World Bank live" : status === "loading" ? "Connecting" : "Demo snapshot"}</div><button className="icon-button" onClick={load} aria-label="Refresh data"><RefreshCw size={16} className={spin ? "spin" : ""} /></button></div></header>
      <div className="control-row"><Tabs value={region} onValueChange={selectRegion}><TabsList className="region-tabs">{["World", "Americas", "Europe", "Asia", "Africa", "Middle East"].map((r) => <TabsTrigger key={r} value={r}>{r}</TabsTrigger>)}</TabsList></Tabs><div className="country-picker"><span>FOCUS</span><Select value={active?.code} onValueChange={setSelected}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent position="popper">{visible.map((c) => <SelectItem key={c.code} value={c.code}>{c.iso2} · {c.name}</SelectItem>)}</SelectContent></Select></div></div>
      <section className="kpi-grid">{[["Combined GDP", fmtMoney(world.totalGdp), `${visible.length} economies`, CircleDollarSign], ["Population", fmtNum(world.totalPop), "people represented", Users], ["Growth pulse", fmtPct(world.growth), "GDP-weighted", Activity], ["Median inflation", fmtPct(world.inflation), "across selection", BarChart3]].map(([label, value, note, Icon], i) => <Card key={String(label)} className="kpi-card"><div className="kpi-top"><span>{label as string}</span><Icon size={17} /></div><strong>{value as string}</strong><small>{note as string}</small><div className="kpi-accent" style={{ background: COLORS[i] }} /></Card>)}</section>
      <section className="main-grid">
        <Card className="top-economies"><div className="panel-head"><div><span className="panel-kicker">MARKET SCALE</span><h2>Largest economies</h2></div><span>USD · trillions</span></div><div className="chart-wrap tall"><ResponsiveContainer width="100%" height="100%"><BarChart data={top} layout="vertical" margin={{ left: 8, right: 30 }}><CartesianGrid horizontal={false} stroke="#263149" strokeDasharray="2 5" /><XAxis type="number" axisLine={false} tickLine={false} tick={{ fill: "#77839c", fontSize: 11 }} /><YAxis type="category" dataKey="name" width={94} axisLine={false} tickLine={false} tick={{ fill: "#c9d2e5", fontSize: 11 }} /><ChartTooltip content={<CustomTooltip />} cursor={{ fill: "rgba(124,140,255,.07)" }} /><Bar dataKey="value" name="GDP" radius={[0, 8, 8, 0]} barSize={14}>{top.map((entry, i) => <Cell key={entry.code} fill={entry.code === active?.code ? "#54e7c2" : COLORS[(top.length - 1 - i) % COLORS.length]} fillOpacity={entry.code === active?.code ? 1 : .62} />)}</Bar></BarChart></ResponsiveContainer></div></Card>
        <Card className="spotlight"><div className="spotlight-top"><div><span className="flag-code">{active?.iso2}</span><div><span className="panel-kicker">COUNTRY SPOTLIGHT</span><h2>{active?.name}</h2></div></div><div className="income-chip">{active?.income}</div></div><div className="spot-stats"><div><span>GDP</span><strong>{fmtMoney(latest(active, "gdp"))}</strong></div><div><span>Per person</span><strong>{fmtMoney(latest(active, "gdpPerCapita"), false)}</strong></div><div><span>Growth</span><strong className={(latest(active, "growth") ?? 0) >= 0 ? "positive" : "negative"}>{fmtPct(latest(active, "growth"))}</strong></div></div><Tabs value={metric} onValueChange={setMetric}><TabsList className="metric-tabs">{Object.entries(METRIC_META).map(([key, m]) => <TabsTrigger value={key} key={key}>{m.label}</TabsTrigger>)}</TabsList></Tabs><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ top: 16, right: 10, left: -14 }}><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={METRIC_META[metric].color} stopOpacity=".42"/><stop offset="1" stopColor={METRIC_META[metric].color} stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#263149" strokeDasharray="2 5" /><XAxis dataKey="year" axisLine={false} tickLine={false} tick={{ fill: "#77839c", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#77839c", fontSize: 11 }} /><ChartTooltip content={<CustomTooltip />} /><Area type="monotone" dataKey="value" name={METRIC_META[metric].label} stroke={METRIC_META[metric].color} strokeWidth={2.5} fill="url(#trendFill)" dot={{ r: 3, fill: "#0f1627", strokeWidth: 2 }} /></AreaChart></ResponsiveContainer></div></Card>
        <Card className="scatter-card"><div className="panel-head"><div><span className="panel-kicker">PROSPERITY × MOMENTUM</span><h2>Growth field</h2></div><span>Bubble = population</span></div><div className="chart-wrap scatter-wrap"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 12, right: 18, bottom: 4 }}><CartesianGrid stroke="#263149" strokeDasharray="2 5" /><XAxis type="number" dataKey="x" name="GDP/person ($k)" unit="k" axisLine={false} tickLine={false} tick={{ fill: "#77839c", fontSize: 11 }} /><YAxis type="number" dataKey="y" name="Growth" unit="%" axisLine={false} tickLine={false} tick={{ fill: "#77839c", fontSize: 11 }} /><ZAxis type="number" dataKey="z" range={[30, 500]} /><ReferenceLine y={0} stroke="#77839c" /><ChartTooltip cursor={{ strokeDasharray: "3 3" }} content={<CustomTooltip />} /><Scatter data={scatter} name="Economies" fill="#7c8cff" fillOpacity={.7}>{scatter.map((d) => <Cell key={d.code} fill={d.code === active?.code ? "#54e7c2" : "#7c8cff"} />)}</Scatter></ScatterChart></ResponsiveContainer></div></Card>
        <Card className="pulse-card"><div className="panel-head"><div><span className="panel-kicker">GLOBAL LEADERS</span><h2>Economic pulse matrix</h2></div><span>Latest available</span></div><div className="matrix"><div className="matrix-row matrix-head"><span>Economy</span><span>Growth</span><span>Inflation</span><span>Jobs gap</span></div>{pulse.map((c) => { const growth = latest(c, "growth"); return <button className={`matrix-row ${c.code === active?.code ? "active" : ""}`} key={c.code} onClick={() => setSelected(c.code)}><span><b>{c.iso2}</b>{c.name}</span><span className={(growth ?? 0) >= 0 ? "positive" : "negative"}>{(growth ?? 0) >= 0 ? <ArrowUpRight size={13}/> : <ArrowDownRight size={13}/>} {fmtPct(growth)}</span><span>{fmtPct(latest(c, "inflation"))}</span><span>{fmtPct(latest(c, "unemployment"))}</span></button>; })}</div></Card>
      </section>
      <footer><span><i className={status} /> {status === "live" ? "World Bank Indicators API" : "Illustrative fallback data"}</span><span>{updatedAt ? `Refreshed ${new Date(updatedAt).toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}` : "Loading latest release"}</span></footer>
    </div>
  </main>;
}
